apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: hheu-smailandstuff
spec:
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "4b523c10-8446-4f2a-aec1-8e527c7e2ec9"
            NODE_ENV: "production"
      secrets:
        - CLIENTSECRET